// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bootService.proto

package com.sample.bootgrpc.api;

public interface BootResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.bootgrpc.BootResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string respName = 1;</code>
   * @return The respName.
   */
  java.lang.String getRespName();
  /**
   * <code>string respName = 1;</code>
   * @return The bytes for respName.
   */
  com.google.protobuf.ByteString
      getRespNameBytes();

  /**
   * <code>int32 respId = 2;</code>
   * @return The respId.
   */
  int getRespId();
}
