// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bootService.proto

package com.sample.bootgrpc.api;

public final class BootMessageProto {
  private BootMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_bootgrpc_BootRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_bootgrpc_BootRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_bootgrpc_BootResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_bootgrpc_BootResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021bootService.proto\022\023com.sample.bootgrpc" +
      "\"\033\n\013BootRequest\022\014\n\004name\030\001 \001(\t\"0\n\014BootRes" +
      "ponse\022\020\n\010respName\030\001 \001(\t\022\016\n\006respId\030\002 \001(\0052" +
      "f\n\013BootService\022W\n\016GiveBootValues\022 .com.s" +
      "ample.bootgrpc.BootRequest\032!.com.sample." +
      "bootgrpc.BootResponse\"\000B-\n\027com.sample.bo" +
      "otgrpc.apiB\020BootMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sample_bootgrpc_BootRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sample_bootgrpc_BootRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_bootgrpc_BootRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_sample_bootgrpc_BootResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sample_bootgrpc_BootResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_bootgrpc_BootResponse_descriptor,
        new java.lang.String[] { "RespName", "RespId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
