// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bootService.proto

package com.sample.bootgrpc.api;

/**
 * Protobuf type {@code com.sample.bootgrpc.BootResponse}
 */
public  final class BootResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sample.bootgrpc.BootResponse)
    BootResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BootResponse.newBuilder() to construct.
  private BootResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BootResponse() {
    respName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BootResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BootResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            respName_ = s;
            break;
          }
          case 16: {

            respId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sample.bootgrpc.api.BootMessageProto.internal_static_com_sample_bootgrpc_BootResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sample.bootgrpc.api.BootMessageProto.internal_static_com_sample_bootgrpc_BootResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sample.bootgrpc.api.BootResponse.class, com.sample.bootgrpc.api.BootResponse.Builder.class);
  }

  public static final int RESPNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object respName_;
  /**
   * <code>string respName = 1;</code>
   * @return The respName.
   */
  public java.lang.String getRespName() {
    java.lang.Object ref = respName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      respName_ = s;
      return s;
    }
  }
  /**
   * <code>string respName = 1;</code>
   * @return The bytes for respName.
   */
  public com.google.protobuf.ByteString
      getRespNameBytes() {
    java.lang.Object ref = respName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      respName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPID_FIELD_NUMBER = 2;
  private int respId_;
  /**
   * <code>int32 respId = 2;</code>
   * @return The respId.
   */
  public int getRespId() {
    return respId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRespNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, respName_);
    }
    if (respId_ != 0) {
      output.writeInt32(2, respId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRespNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, respName_);
    }
    if (respId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, respId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sample.bootgrpc.api.BootResponse)) {
      return super.equals(obj);
    }
    com.sample.bootgrpc.api.BootResponse other = (com.sample.bootgrpc.api.BootResponse) obj;

    if (!getRespName()
        .equals(other.getRespName())) return false;
    if (getRespId()
        != other.getRespId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRespName().hashCode();
    hash = (37 * hash) + RESPID_FIELD_NUMBER;
    hash = (53 * hash) + getRespId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sample.bootgrpc.api.BootResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sample.bootgrpc.api.BootResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sample.bootgrpc.api.BootResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sample.bootgrpc.api.BootResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sample.bootgrpc.BootResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sample.bootgrpc.BootResponse)
      com.sample.bootgrpc.api.BootResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sample.bootgrpc.api.BootMessageProto.internal_static_com_sample_bootgrpc_BootResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sample.bootgrpc.api.BootMessageProto.internal_static_com_sample_bootgrpc_BootResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sample.bootgrpc.api.BootResponse.class, com.sample.bootgrpc.api.BootResponse.Builder.class);
    }

    // Construct using com.sample.bootgrpc.api.BootResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      respName_ = "";

      respId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sample.bootgrpc.api.BootMessageProto.internal_static_com_sample_bootgrpc_BootResponse_descriptor;
    }

    @java.lang.Override
    public com.sample.bootgrpc.api.BootResponse getDefaultInstanceForType() {
      return com.sample.bootgrpc.api.BootResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sample.bootgrpc.api.BootResponse build() {
      com.sample.bootgrpc.api.BootResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sample.bootgrpc.api.BootResponse buildPartial() {
      com.sample.bootgrpc.api.BootResponse result = new com.sample.bootgrpc.api.BootResponse(this);
      result.respName_ = respName_;
      result.respId_ = respId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sample.bootgrpc.api.BootResponse) {
        return mergeFrom((com.sample.bootgrpc.api.BootResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sample.bootgrpc.api.BootResponse other) {
      if (other == com.sample.bootgrpc.api.BootResponse.getDefaultInstance()) return this;
      if (!other.getRespName().isEmpty()) {
        respName_ = other.respName_;
        onChanged();
      }
      if (other.getRespId() != 0) {
        setRespId(other.getRespId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sample.bootgrpc.api.BootResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sample.bootgrpc.api.BootResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object respName_ = "";
    /**
     * <code>string respName = 1;</code>
     * @return The respName.
     */
    public java.lang.String getRespName() {
      java.lang.Object ref = respName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        respName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string respName = 1;</code>
     * @return The bytes for respName.
     */
    public com.google.protobuf.ByteString
        getRespNameBytes() {
      java.lang.Object ref = respName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string respName = 1;</code>
     * @param value The respName to set.
     * @return This builder for chaining.
     */
    public Builder setRespName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      respName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string respName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRespName() {
      
      respName_ = getDefaultInstance().getRespName();
      onChanged();
      return this;
    }
    /**
     * <code>string respName = 1;</code>
     * @param value The bytes for respName to set.
     * @return This builder for chaining.
     */
    public Builder setRespNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      respName_ = value;
      onChanged();
      return this;
    }

    private int respId_ ;
    /**
     * <code>int32 respId = 2;</code>
     * @return The respId.
     */
    public int getRespId() {
      return respId_;
    }
    /**
     * <code>int32 respId = 2;</code>
     * @param value The respId to set.
     * @return This builder for chaining.
     */
    public Builder setRespId(int value) {
      
      respId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 respId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRespId() {
      
      respId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sample.bootgrpc.BootResponse)
  }

  // @@protoc_insertion_point(class_scope:com.sample.bootgrpc.BootResponse)
  private static final com.sample.bootgrpc.api.BootResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sample.bootgrpc.api.BootResponse();
  }

  public static com.sample.bootgrpc.api.BootResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BootResponse>
      PARSER = new com.google.protobuf.AbstractParser<BootResponse>() {
    @java.lang.Override
    public BootResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BootResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BootResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BootResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sample.bootgrpc.api.BootResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

